### ISSUE TITLE
New Health System

### ISSUE THREAD

**Issue by Plutzz** [Plutzz/TheLittleThings#11]
- [x] Create a new C# script (IDamageable)
   - [x] This script will NOT inherit from monobehavior
   - [x] Instead the script will be an interface: "public interface IDamageable"
   - [x] In this interface, define the following methods
      - [x] TakeDamage(int _damage)
      - [x] TakeDamage(int _damage, int _invincibilityFrames)
      - [x] Die()
   - [x] Then make another C# script that implments the interface (EnemyHealth : Monobehavior, IDamageable)
      - [x] Has a int maxHealth and int currentHealth
      - [x] on start it makes currentHealth = maxHealth
      - [x] implment TakeDamage(int _damage) and Die() methods (ignore second take damage implmentation for now)
         - [x] TakeDamage(int _damage)
            - [x] Subtracts _damage from currentHealth
            - [x] if currentHealth < 0, invoke the Die() method
         - [x] Die()
            - [x] just destroy the game object lol

**Comment by kaleyvuong** [comment]
what do you want me to implement for the take damage and die methods like do i just make the current health decrease
