### ISSUE TITLE
Roll state

### ISSUE THREAD

**Issue by Plutzz** [Plutzz/TheLittleThings#12]
- [x] Create a new C# script in the scripts folder called PlayerRollState
- [x] Make PlayerRollState : State (inherit from state base class)
- [x] When the player enters the rolling state (public override void DoEnterLogic())
   - [x] Start rolling animation (look around in the other state scripts and the player animator to figure out how to do that)
- [x] Make the player move in the direction that they are pressing (or facing if they aren't pressing anything) at a set speed for a set time
- [x] Once the set time has elapsed mark the state as complete (in that class you should have access to a variable called IsComplete)
- [x] In the Player script (the one that inherits from StateMachineCore), transition into the roll state if the player presses shift and they are in Idle or Move states

- NOTES: I documented the state, statemachine, and statemachinecore classes pretty well so if you feel stuck looking at those might help!

**Comment by Its-Cryptic** [comment]
Merged into main [Roll State Complete](https://github.com/Plutzz/TheLittleThings/commit/4183863ac93c0cf34fc6b2d434223ee7380d3696)
