### ISSUE TITLE
Resource System

### ISSUE THREAD

**Issue by Plutzz** [Plutzz/TheLittleThings#8]
- [x] PlayerResources : ScriptableObject
    - [x] Resource wood = new Resource();

- [x] Resource : ScriptableObject
   - [x] ID
   - [x] Name
   - [x] Description
   - [x] Sprite
   - [x] Count

- [ ] Bosses drop resources on kill
   - [ ] For now just make it pop up in the UI

**Comment by Nerd-eee** [comment]
Recommend move bosses drop resources on kill to a quest complete

**Comment by Nerd-eee** [comment]
Need to fix slight issue of thing breaking at runtime due to manager not setting itself up for some reason
